package com.ksign.zzangdol.score;
import java.util.HashMap;
import java.util.Map;


public class Score {
	private static Map<String, int[]> attackScoreMap = new HashMap<String, int[]>();
	private static Map<String, int[]> defenceScoreMap = new HashMap<String, int[]>();

	public static final int THREE_THREE_ATTACK_SCORE = 67;
	public static final int THREE_THREE_DEFENCE_SCORE = 60;
	
	public static String print() {
		StringBuilder sb = new StringBuilder();
		boolean isFirst = true;
		for(Map.Entry<String, int[]> entry : attackScoreMap.entrySet()) {
			if(isFirst) isFirst = false;
			else sb.append(",");
			sb.append(entry.getKey()).append("=");
			for(int i=0; i<entry.getValue().length; i++) {
				if(i>0) sb.append(",");
				sb.append(entry.getValue()[i]);
			}
		}
		return sb.toString();
	}

	public static Map<String, int[]> getScoreMap() {
		return attackScoreMap;
	}

	public static Map<String, int[]> getDefenceScoreMap() {
		return defenceScoreMap;
	}
	
	static {
		attackScoreMap.put("-------", new int[]{0,0,0,0,0});
		attackScoreMap.put("-----o-", new int[]{1,2,2,3,0});
		attackScoreMap.put("----o--", new int[]{2,2,3,0,3});
		attackScoreMap.put("----oo-", new int[]{3,3,4,0,0});
		attackScoreMap.put("---o---", new int[]{2,3,0,3,2});
		attackScoreMap.put("---o-o-", new int[]{2,4,0,4,0});
		attackScoreMap.put("---oo--", new int[]{3,4,0,0,4});
		attackScoreMap.put("---ooo-", new int[]{6,7,0,0,0});
		attackScoreMap.put("--o----", new int[]{3,0,3,2,2});
		attackScoreMap.put("--o--o-", new int[]{3,0,4,4,0});
		attackScoreMap.put("--o-o--", new int[]{4,0,4,0,4});
		attackScoreMap.put("--o-oo-", new int[]{5,0,7,0,0});
		attackScoreMap.put("--oo---", new int[]{4,0,0,4,3});
		attackScoreMap.put("--oo-o-", new int[]{6,0,0,7,0});
		attackScoreMap.put("--ooo--", new int[]{7,0,0,0,7});
		attackScoreMap.put("--oooo-", new int[]{8,0,0,0,0});
		attackScoreMap.put("-o-----", new int[]{0,3,2,2,1});
		attackScoreMap.put("-o---o-", new int[]{0,3,3,3,0});
		attackScoreMap.put("-o--o--", new int[]{0,4,4,0,3});
		attackScoreMap.put("-o--oo-", new int[]{0,5,6,0,0});
		attackScoreMap.put("-o-o---", new int[]{0,4,0,4,3});
		attackScoreMap.put("-o-o-o-", new int[]{0,6,0,6,0});
		attackScoreMap.put("-o-oo--", new int[]{0,7,0,0,6});
		attackScoreMap.put("-o-ooo-", new int[]{0,8,0,0,0});
		attackScoreMap.put("-oo----", new int[]{0,0,4,3,3});
		attackScoreMap.put("-oo--o-", new int[]{0,0,6,5,0});
		attackScoreMap.put("-oo-o--", new int[]{0,0,7,0,5});
		attackScoreMap.put("-oo-oo-", new int[]{0,0,8,0,0});
		attackScoreMap.put("-ooo---", new int[]{0,0,0,7,6});
		attackScoreMap.put("-ooo-o-", new int[]{0,0,0,8,0});
		attackScoreMap.put("-oooo--", new int[]{0,0,0,0,8});
		attackScoreMap.put("------x", new int[]{0,0,0,0,0});
		attackScoreMap.put("-----ox", new int[]{0,0,1,1,0});
		attackScoreMap.put("----o-x", new int[]{1,1,2,0,1});
		attackScoreMap.put("----oox", new int[]{2,2,3,0,0});
		attackScoreMap.put("---o--x", new int[]{2,3,0,2,1});
		attackScoreMap.put("---o-ox", new int[]{3,3,0,3,0});
		attackScoreMap.put("---oo-x", new int[]{3,4,0,0,3});
		attackScoreMap.put("---ooox", new int[]{4,5,0,0,0});
		attackScoreMap.put("--o---x", new int[]{3,0,3,2,1});
		attackScoreMap.put("--o--ox", new int[]{3,0,3,3,0});
		attackScoreMap.put("--o-o-x", new int[]{4,0,4,0,3});
		attackScoreMap.put("--o-oox", new int[]{5,0,5,0,0});
		attackScoreMap.put("--oo--x", new int[]{4,0,0,4,3});
		attackScoreMap.put("--oo-ox", new int[]{6,0,0,5,0});
		attackScoreMap.put("--ooo-x", new int[]{7,0,0,0,5});
		attackScoreMap.put("--oooox", new int[]{8,0,0,0,0});
		attackScoreMap.put("-o----x", new int[]{0,3,2,2,1});
		attackScoreMap.put("-o---ox", new int[]{0,3,3,2,0});
		attackScoreMap.put("-o--o-x", new int[]{0,4,4,0,3});
		attackScoreMap.put("-o--oox", new int[]{0,5,5,0,0});
		attackScoreMap.put("-o-o--x", new int[]{0,4,0,4,3});
		attackScoreMap.put("-o-o-ox", new int[]{0,6,0,5,0});
		attackScoreMap.put("-o-oo-x", new int[]{0,7,0,0,5});
		attackScoreMap.put("-o-ooox", new int[]{0,8,0,0,0});
		attackScoreMap.put("-oo---x", new int[]{0,0,4,3,3});
		attackScoreMap.put("-oo--ox", new int[]{0,0,6,5,0});
		attackScoreMap.put("-oo-o-x", new int[]{0,0,7,0,5});
		attackScoreMap.put("-oo-oox", new int[]{0,0,8,0,0});
		attackScoreMap.put("-ooo--x", new int[]{0,0,0,7,6});
		attackScoreMap.put("-ooo-ox", new int[]{0,0,0,8,0});
		attackScoreMap.put("-oooo-x", new int[]{0,0,0,0,8});
		attackScoreMap.put("x------", new int[]{0,0,0,0,0});
		attackScoreMap.put("x----o-", new int[]{1,2,2,3,0});
		attackScoreMap.put("x---o--", new int[]{1,2,3,0,3});
		attackScoreMap.put("x---oo-", new int[]{3,3,4,0,0});
		attackScoreMap.put("x--o---", new int[]{1,2,0,3,2});
		attackScoreMap.put("x--o-o-", new int[]{3,4,0,4,0});
		attackScoreMap.put("x--oo--", new int[]{3,4,0,0,4});
		attackScoreMap.put("x--ooo-", new int[]{6,7,0,0,0});
		attackScoreMap.put("x-o----", new int[]{1,0,3,2,1});
		attackScoreMap.put("x-o--o-", new int[]{3,0,4,4,0});
		attackScoreMap.put("x-o-o--", new int[]{3,0,4,0,4});
		attackScoreMap.put("x-o-oo-", new int[]{5,0,7,0,0});
		attackScoreMap.put("x-oo---", new int[]{3,0,0,4,3});
		attackScoreMap.put("x-oo-o-", new int[]{5,0,0,7,0});
		attackScoreMap.put("x-ooo--", new int[]{5,0,0,0,7});
		attackScoreMap.put("x-oooo-", new int[]{8,0,0,0,0});
		attackScoreMap.put("xo-----", new int[]{0,1,0,0,0});
		attackScoreMap.put("xo---o-", new int[]{0,3,2,3,0});
		attackScoreMap.put("xo--o--", new int[]{0,3,3,0,3});
		attackScoreMap.put("xo--oo-", new int[]{0,5,6,0,0});
		attackScoreMap.put("xo-o---", new int[]{0,3,0,3,3});
		attackScoreMap.put("xo-o-o-", new int[]{0,5,0,6,0});
		attackScoreMap.put("xo-oo--", new int[]{0,5,0,0,6});
		attackScoreMap.put("xo-ooo-", new int[]{0,8,0,0,0});
		attackScoreMap.put("xoo----", new int[]{0,0,3,2,2});
		attackScoreMap.put("xoo--o-", new int[]{0,0,5,5,0});
		attackScoreMap.put("xoo-o--", new int[]{0,0,5,0,4});
		attackScoreMap.put("xoo-oo-", new int[]{0,0,8,0,0});
		attackScoreMap.put("xooo---", new int[]{0,0,0,5,4});
		attackScoreMap.put("xooo-o-", new int[]{0,0,0,8,0});
		attackScoreMap.put("xoooo--", new int[]{0,0,0,0,8});
		attackScoreMap.put("x-----x", new int[]{0,0,0,0,0});
		attackScoreMap.put("x----ox", new int[]{1,1,1,1,0}); 
		attackScoreMap.put("x---o-x", new int[]{1,1,1,0,1});
		attackScoreMap.put("x---oox", new int[]{2,2,3,0,0});
		attackScoreMap.put("x--o--x", new int[]{0,1,0,1,0});
		attackScoreMap.put("x--o-ox", new int[]{2,3,0,3,0});
		attackScoreMap.put("x--oo-x", new int[]{2,3,0,0,3});
		attackScoreMap.put("x--ooox", new int[]{4,5,0,0,0});
		attackScoreMap.put("x-o---x", new int[]{1,0,1,1,1});
		attackScoreMap.put("x-o--ox", new int[]{3,0,3,3,0});
		attackScoreMap.put("x-o-o-x", new int[]{3,0,4,0,3});
		attackScoreMap.put("x-o-oox", new int[]{5,0,5,0,0});
		attackScoreMap.put("x-oo--x", new int[]{3,0,0,3,2});
		attackScoreMap.put("x-oo-ox", new int[]{5,0,0,5,0});
		attackScoreMap.put("x-ooo-x", new int[]{5,0,0,0,5});
		attackScoreMap.put("x-oooox", new int[]{8,0,0,0,0});
		attackScoreMap.put("xo----x", new int[]{0,1,1,1,1});
		attackScoreMap.put("xo---ox", new int[]{0,3,2,3,0});
		attackScoreMap.put("xo--o-x", new int[]{0,2,3,0,2});
		attackScoreMap.put("xo--oox", new int[]{0,5,5,0,0});
		attackScoreMap.put("xo-o--x", new int[]{0,3,0,3,3});
		attackScoreMap.put("xo-o-ox", new int[]{0,5,0,5,0});
		attackScoreMap.put("xo-oo-x", new int[]{0,5,0,0,5});
		attackScoreMap.put("xo-ooox", new int[]{0,8,0,0,0});
		attackScoreMap.put("xoo---x", new int[]{0,0,3,2,2});
		attackScoreMap.put("xoo--ox", new int[]{0,0,5,5,0});
		attackScoreMap.put("xoo-o-x", new int[]{0,0,5,0,5});
		attackScoreMap.put("xoo-oox", new int[]{0,0,8,0,0});
		attackScoreMap.put("xooo--x", new int[]{0,0,0,5,4});
		attackScoreMap.put("xooo-ox", new int[]{0,0,0,8,0});
		attackScoreMap.put("xoooo-x", new int[]{0,0,0,0,8});
		
		defenceScoreMap.put("-------", new int[]{0,0,0,0,0});
		defenceScoreMap.put("-----o-", new int[]{0,0,0,1,0});
		defenceScoreMap.put("----o--", new int[]{0,0,1,0,1});
		defenceScoreMap.put("----oo-", new int[]{1,1,2,0,0});
		defenceScoreMap.put("---o---", new int[]{0,1,0,1,0});
		defenceScoreMap.put("---o-o-", new int[]{1,2,0,2,0});
		defenceScoreMap.put("---oo--", new int[]{0,2,0,0,2});
		defenceScoreMap.put("---ooo-", new int[]{6,7,0,0,0});
		defenceScoreMap.put("--o----", new int[]{0,0,1,0,0});
		defenceScoreMap.put("--o--o-", new int[]{1,0,2,2,0});
		defenceScoreMap.put("--o-o--", new int[]{2,0,2,0,2});
		defenceScoreMap.put("--o-oo-", new int[]{4,0,6,0,0});
		defenceScoreMap.put("--oo---", new int[]{2,0,0,2,1});
		defenceScoreMap.put("--oo-o-", new int[]{5,0,0,6,0});
		defenceScoreMap.put("--ooo--", new int[]{6,0,0,0,6});
		defenceScoreMap.put("--oooo-", new int[]{8,0,0,0,0});
		defenceScoreMap.put("-o-----", new int[]{0,1,0,0,0});
		defenceScoreMap.put("-o---o-", new int[]{0,1,0,1,0});
		defenceScoreMap.put("-o--o--", new int[]{0,2,2,0,1});
		defenceScoreMap.put("-o--oo-", new int[]{0,4,5,0,0});
		defenceScoreMap.put("-o-o---", new int[]{0,2,0,2,1});
		defenceScoreMap.put("-o-o-o-", new int[]{0,5,0,5,0});
		defenceScoreMap.put("-o-oo--", new int[]{0,7,0,0,6});
		defenceScoreMap.put("-o-ooo-", new int[]{0,8,0,0,0});
		defenceScoreMap.put("-oo----", new int[]{0,0,2,1,0});
		defenceScoreMap.put("-oo--o-", new int[]{0,0,5,4,0});
		defenceScoreMap.put("-oo-o--", new int[]{0,0,6,0,4});
		defenceScoreMap.put("-oo-oo-", new int[]{0,0,8,0,0});
		defenceScoreMap.put("-ooo---", new int[]{0,0,0,6,5});
		defenceScoreMap.put("-ooo-o-", new int[]{0,0,0,8,0});
		defenceScoreMap.put("-oooo--", new int[]{0,0,0,0,8});
		defenceScoreMap.put("------x", new int[]{0,0,0,0,0});
		defenceScoreMap.put("-----ox", new int[]{0,0,0,1,0});
		defenceScoreMap.put("----o-x", new int[]{0,0,1,0,0});
		defenceScoreMap.put("----oox", new int[]{0,1,2,0,0});
		defenceScoreMap.put("---o--x", new int[]{0,1,0,2,0});
		defenceScoreMap.put("---o-ox", new int[]{1,2,0,2,0});
		defenceScoreMap.put("---oo-x", new int[]{0,2,0,0,1});
		defenceScoreMap.put("---ooox", new int[]{4,5,0,0,0});
		defenceScoreMap.put("--o---x", new int[]{1,0,1,0,0});
		defenceScoreMap.put("--o--ox", new int[]{2,0,2,2,0});
		defenceScoreMap.put("--o-o-x", new int[]{2,0,2,0,1});
		defenceScoreMap.put("--o-oox", new int[]{4,0,4,0,0});
		defenceScoreMap.put("--oo--x", new int[]{2,0,0,2,3});
		defenceScoreMap.put("--oo-ox", new int[]{5,0,0,4,0});
		defenceScoreMap.put("--ooo-x", new int[]{6,0,0,0,5});
		defenceScoreMap.put("--oooox", new int[]{8,0,0,0,0});
		defenceScoreMap.put("-o----x", new int[]{0,1,0,0,0});
		defenceScoreMap.put("-o---ox", new int[]{0,1,0,1,0});
		defenceScoreMap.put("-o--o-x", new int[]{0,2,2,0,0});
		defenceScoreMap.put("-o--oox", new int[]{0,4,4,0,0});
		defenceScoreMap.put("-o-o--x", new int[]{0,2,0,2,1});
		defenceScoreMap.put("-o-o-ox", new int[]{0,5,0,4,0});
		defenceScoreMap.put("-o-oo-x", new int[]{0,6,0,0,4});
		defenceScoreMap.put("-o-ooox", new int[]{0,8,0,0,0});
		defenceScoreMap.put("-oo---x", new int[]{0,0,2,0,1});
		defenceScoreMap.put("-oo--ox", new int[]{0,0,5,4,0});
		defenceScoreMap.put("-oo-o-x", new int[]{0,0,6,0,4});
		defenceScoreMap.put("-oo-oox", new int[]{0,0,8,0,0});
		defenceScoreMap.put("-ooo--x", new int[]{0,0,0,6,5});
		defenceScoreMap.put("-ooo-ox", new int[]{0,0,0,8,0});
		defenceScoreMap.put("-oooo-x", new int[]{0,0,0,0,8});
		defenceScoreMap.put("x------", new int[]{0,0,0,0,0});
		defenceScoreMap.put("x----o-", new int[]{0,0,0,1,0});
		defenceScoreMap.put("x---o--", new int[]{0,0,1,0,1});
		defenceScoreMap.put("x---oo-", new int[]{0,1,2,0,0});
		defenceScoreMap.put("x--o---", new int[]{0,1,0,1,0});
		defenceScoreMap.put("x--o-o-", new int[]{1,2,0,2,0});
		defenceScoreMap.put("x--oo--", new int[]{1,2,0,0,2});
		defenceScoreMap.put("x--ooo-", new int[]{5,6,0,0,0});
		defenceScoreMap.put("x-o----", new int[]{1,0,1,0,0});
		defenceScoreMap.put("x-o--o-", new int[]{1,0,2,2,0});
		defenceScoreMap.put("x-o-o--", new int[]{1,0,2,0,2});
		defenceScoreMap.put("x-o-oo-", new int[]{4,0,6,0,0});
		defenceScoreMap.put("x-oo---", new int[]{3,0,0,2,1});
		defenceScoreMap.put("x-oo-o-", new int[]{4,0,0,6,0});
		defenceScoreMap.put("x-ooo--", new int[]{4,0,0,0,6});
		defenceScoreMap.put("x-oooo-", new int[]{8,0,0,0,0});
		defenceScoreMap.put("xo-----", new int[]{0,1,0,0,0});
		defenceScoreMap.put("xo---o-", new int[]{0,1,1,2,0});
		defenceScoreMap.put("xo--o--", new int[]{0,1,2,0,2});
		defenceScoreMap.put("xo--oo-", new int[]{0,4,5,0,0});
		defenceScoreMap.put("xo-o---", new int[]{0,1,0,2,1});
		defenceScoreMap.put("xo-o-o-", new int[]{0,4,0,5,0});
		defenceScoreMap.put("xo-oo--", new int[]{0,4,0,0,5});
		defenceScoreMap.put("xo-ooo-", new int[]{0,8,0,0,0});
		defenceScoreMap.put("xoo----", new int[]{0,0,2,1,0});
		defenceScoreMap.put("xoo--o-", new int[]{0,0,4,4,0});
		defenceScoreMap.put("xoo-o--", new int[]{0,0,4,0,4});
		defenceScoreMap.put("xoo-oo-", new int[]{0,0,8,0,0});
		defenceScoreMap.put("xooo---", new int[]{0,0,0,4,3});
		defenceScoreMap.put("xooo-o-", new int[]{0,0,0,8,0});
		defenceScoreMap.put("xoooo--", new int[]{0,0,0,0,8});
		defenceScoreMap.put("x-----x", new int[]{0,0,0,0,0});
		defenceScoreMap.put("x----ox", new int[]{0,0,0,1,0});
		defenceScoreMap.put("x---o-x", new int[]{0,0,1,0,1});
		defenceScoreMap.put("x---oox", new int[]{0,0,2,0,0});
		defenceScoreMap.put("x--o--x", new int[]{0,1,0,1,0});
		defenceScoreMap.put("x--o-ox", new int[]{1,2,0,2,0});
		defenceScoreMap.put("x--oo-x", new int[]{1,2,0,0,2});
		defenceScoreMap.put("x--ooox", new int[]{3,4,0,0,0});
		defenceScoreMap.put("x-o---x", new int[]{1,0,1,0,0});
		defenceScoreMap.put("x-o--ox", new int[]{1,0,2,2,0});
		defenceScoreMap.put("x-o-o-x", new int[]{2,0,2,0,2});
		defenceScoreMap.put("x-o-oox", new int[]{4,0,4,0,0});
		defenceScoreMap.put("x-oo--x", new int[]{2,0,0,2,2});
		defenceScoreMap.put("x-oo-ox", new int[]{4,0,0,4,0});
		defenceScoreMap.put("x-ooo-x", new int[]{4,0,0,0,4});
		defenceScoreMap.put("x-oooox", new int[]{8,0,0,0,0});
		defenceScoreMap.put("xo----x", new int[]{0,1,0,0,1});
		defenceScoreMap.put("xo---ox", new int[]{0,2,2,2,0});
		defenceScoreMap.put("xo--o-x", new int[]{0,1,2,0,1});
		defenceScoreMap.put("xo--oox", new int[]{0,4,4,0,0});
		defenceScoreMap.put("xo-o--x", new int[]{0,2,0,2,2});
		defenceScoreMap.put("xo-o-ox", new int[]{0,4,0,4,0});
		defenceScoreMap.put("xo-oo-x", new int[]{0,4,0,0,4});
		defenceScoreMap.put("xo-ooox", new int[]{0,8,0,0,0});
		defenceScoreMap.put("xoo---x", new int[]{0,0,2,2,2});
		defenceScoreMap.put("xoo--ox", new int[]{0,0,4,4,0});
		defenceScoreMap.put("xoo-o-x", new int[]{0,0,4,0,4});
		defenceScoreMap.put("xoo-oox", new int[]{0,0,8,0,0});
		defenceScoreMap.put("xooo--x", new int[]{0,0,0,4,4});
		defenceScoreMap.put("xooo-ox", new int[]{0,0,0,8,0});
		defenceScoreMap.put("xoooo-x", new int[]{0,0,0,0,8});
	}
}